sudo: false
language: node_js
node_js:
  - 'stable'
addons:
  code_climate:
    repo_token:
      secure: "h/zmynN4Ku7gy15GrZbUN75kqtltMh1Fzmq0NUGY3LWE/Ct+43LDVYpATNEnDFmYAJjfqao/c5X/4hjdfgp3aQTRYOFxJ3ihaGCA2WYXy5W2Ct9PRv0Mdk2kyh60lZiR8C/eWL9xLnB68Sr9WSPgeD0W53a00T0X8LzyQeD7asupDc6F/JHL6Kd4jtGXIJwJ77QDDFyDBqTkOqJ/Lh5v/2Ugn5ggKZmYgbwvDW2CRs7bLcpcG8MRSPclnN3G+aTnYBwJ4lup7RPoJG3XIjoE07KZvA2+U+PoNi2qi//rJLVvypQ3abIQWUHkue5UP3wdZAcTuBaMAMpy2yVqHX2Da8wbFrS6FuVGm2UNtqGs3NthTc6SnfiXhH+v+dRozYiYtLk67ITYvdCAxw+jYADb0I3jXfpi6vArtu8INt2k4lznMMyRrYHx2IRtgxy2x1z8Qt1N1hXcsavGm7FtXKJxB551HhBrbQfKbeqgigQXVh8/EjcanitlSuMxBa6jfM+MFbmHTfZVe9Yy68VaX4mdJVeab6EbhwpqjXELELQwo2ri/mrLp1giHBBRreYCvZpfq1a7STuqTV5KpB7JdBhG92dosgEbd+rF8N5ARSZVJj0J+luvHTkfHq4wTlp2y6sbwHL/znF0QDOUnSI0rATf0M4hZ+OYDRRQeA0Rk4Q4hJg="
before_script:
  - npm install codeclimate-test-reporter -g
script:
  - npm run test:coverage
after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info
